apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
  labels:
    app: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: rborad/container1:Kube
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
        volumeMounts:
        - name: persistent-storage
          mountPath: /rushil_PV_dir
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pvc-rushil
---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  type: LoadBalancer
  selector:
    app: container1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
